### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by webmaster442** [webmaster442/media#16]
- [x] MPV builder is used in mpv related commands
- [x] Implement caching for randomplay, to filter out allready played commands
- [x] Implement a cache management command: Delete cache
- [ ] Caching is an interface
- [x] Extend play command: If a directory is specified, then all files that are compatible are sent to the player
- [x] For the previous one the scanning creates a playlist in m3u format.
- [x] Add a command that when executed opens the github page of the tool
